src/server/core/security/pom.xml
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/ExpressionUserMapper.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/GrantedAuthoritiesMapper.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/SimpleGrantedAuthoritiesMapper.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/UserDetailsWithAttributes.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/UserMapper.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/ldap/CustomAttributesLdapUserDetailsMapper.java
src/server/core/security/src/main/java/it/geosolutions/geostore/core/security/ldap/LdapUserDetailsWithAttributes.java
src/server/core/security/src/test/java/it/geosolutions/geostore/core/security/ExpressionUserMapperTest.java
src/server/core/security/src/test/java/it/geosolutions/geostore/core/security/MockUserDetailsWithAttributes.java
src/server/core/security/src/test/java/it/geosolutions/geostore/core/security/SimpleGrantedAuthoritiesMapperTest.java
src/server/core/security/src/test/java/it/geosolutions/geostore/core/security/ldap/CustomAttributesLdapUserDetailsMapperTest.java
src/server/core/security/src/test/java/it/geosolutions/geostore/core/security/ldap/MockDirContextOperations.java
src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/GeoStoreLdapAuthoritiesPopulator.java
src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserLdapAuthenticationProvider.java

Various improvements to LDAP Authentication Provider and Authorities Populator
see #98, #100, #101, #102

Various improvements to LDAP Authentication Provider and Authorities Populator

---

src/server/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ResourceDAO.java
src/server/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/ResourceDAOImpl.java
src/server/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourceService.java
src/server/core/services-api/src/main/java/it/geosolutions/geostore/services/exception/DuplicatedResourceNameServiceEx.java
src/server/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
src/server/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourceServiceImplTest.java
src/server/core/services-impl/src/test/java/it/geosolutions/geostore/services/UserGroupServiceImplTest.java
src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTBackupServiceImpl.java
src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTResourceServiceImpl.java

Implemented as discussed in topic [Proposed fix for issue #63: Resource Copy](https://groups.google.com/forum/#!topic/mapstore-developers/nMCDbrSb7B4) at [mapstore-developers Google Group](https://groups.google.com/forum/#!forum/mapstore-developers).

Bugfix for issue #30 (Resource copy)

---

src/server/core/services-api/src/main/java/it/geosolutions/geostore/services/UserGroupService.java
src/server/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
src/server/modules/rest/client/src/main/java/it/geosolutions/geostore/services/rest/AdministratorGeoStoreClient.java
src/server/modules/rest/client/src/main/java/it/geosolutions/geostore/services/rest/GeoStoreClient.java
src/server/modules/rest/client/src/main/java/it/geosolutions/geostore/services/rest/client/model/ExtGroupList.java
src/server/modules/rest/client/src/test/java/it/geosolutions/geostore/services/rest/AdministratorGeostoreClientTest.java
src/server/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/model/ExtGroupList.java
src/server/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/RESTExtJsService.java
src/server/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java

added to /geostore/rest/extjs/search/ the resurce groups/{nameLike}
that allows group searcing by name with pagination.

Improvement for ExtJs REST API

---

src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingTestsUtils.java

This solve audit module windows build tests fails:
http://winbuild.geo-solutions.it/jenkins/job/GeoStore-Master/lastBuild/testReport/

Corretly handle windows new lines

---

src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditInfoExtractorTest.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingConfigurationTest.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingFilesManagerTest.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingOutputTest.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingTemplatesTest.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingTestsBase.java
src/modules/rest/auditing/src/test/java/it/geosolutions/geostore/services/rest/auditing/AuditingTestsUtils.java

Associated issues: #145 and #147.

Fix auditing tests

---

.travis.yml

Please wait for the travis build to finish before merging

Drop Oracle JDK7 from travis as it is not available anymore

---

.travis.yml
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/SessionTokenAuthenticationFilter.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/SessionTokenAuthenticationFilterTest.java

fix #185
Retrieve user from db by username, if id is still missing in auth context

fix #185 Login fail on first attempt using LDAP

---

README.md

Remove winbuild build status

---

pom.xml
src/core/model/pom.xml
src/core/persistence/pom.xml
src/core/pom.xml
src/core/security/pom.xml
src/core/services-api/pom.xml
src/core/services-impl/pom.xml
src/modules/pom.xml
src/modules/rest/api/pom.xml
src/modules/rest/auditing/pom.xml
src/modules/rest/client/pom.xml
src/modules/rest/extjs/pom.xml
src/modules/rest/impl/pom.xml
src/modules/rest/pom.xml
src/modules/rest/test/pom.xml
src/pom.xml
src/web/app/pom.xml
src/web/pom.xml

This updates on master branch the version to 1.6-SNAPSHOT.
I wrote and follow this procedure. 
https://github.com/geosolutions-it/geostore/wiki/Release-Process
You can see version 1.5 published

Updated geostore versions to 1.6

---

src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourceServiceImplTest.java

This PR sorts by default all resources search results sorted by name.

Sort resources by name

---

src/pom.xml

Upgrading log4j to a version that does not support RCEs

---

src/modules/rest/impl/pom.xml
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/WebServiceTokenAuthenticationFilter.java
src/pom.xml
src/web/app/pom.xml

This is backport of PR [250](https://github.com/geosolutions-it/geostore/pull/250) for branch 1.7.x

[Backport 1.7.x] Corporate proxy issue prevents connections between MS and GN

---

src/modules/rest/impl/pom.xml
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/WebServiceTokenAuthenticationFilter.java
src/pom.xml
src/web/app/pom.xml

This is backport of PR [250](https://github.com/geosolutions-it/geostore/pull/250) for branch 1.6.x

[Backport 1.6.x] Corporate proxy issue prevents connections between MS and GN

---

src/pom.xml

bump spring version

---

src/core/security/src/test/java/it/geosolutions/geostore/core/security/SimpleGrantedAuthoritiesMapperTest.java

Included UI test for dropping unmapped roles

Issue #265 - included test dropUnmappedRoles

---

src/pom.xml

Backport to 1.8.x the spring, hibernate and hibernate-dao dependencies bumping.

[1.8.x backport] spring and hibernate dependencies bumping

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreOAuthAuthenticator.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakConfiguration.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakLoginService.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakSessionServiceDelegate.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/Oauth2LoginService.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/KeycloakFilterTest.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/KeycloakLoginTest.java
src/web/app/src/main/resources/geostore-ovr.properties

- use cookies as a token store for keycloak 
- remove cookie addition in login endpoint

fix jsessionid

---

src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/RESTSessionService.java

- make the refresh token endpoint available for anonymous users

authorize anonymous on refresh token endpoint

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakSessionServiceDelegate.java

- remove the post logut redirect setting in keycloak since it is not needed.

remove keycloak post logout redirect

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/AuthoritiesMappings.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/BaseKeycloakDAO.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthoritiesMapper.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreOAuthAuthenticator.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakConfiguration.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakCookieUtils.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakSessionServiceDelegate.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakUserDAO.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakUserGroupDAO.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/google/OAuthGoogleSecurityConfiguration.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/KeycloakFilterTest.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/KeycloakTestSupport.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/MockUserGroupService.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/MockUserService.java
src/web/app/src/main/resources/geostore-ovr.properties

- synch keycloak roles not mapped as geostore roles to geostore user groups.

synch groups with keycloak

---

src/core/persistence/pom.xml
src/core/security/pom.xml
src/core/services-api/pom.xml
src/core/services-impl/pom.xml
src/pom.xml

- Removed dom4j dependancy. Now it comes transitively with hibernate-core

Cleared out redundant dom4j dependency

---

src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/service/impl/RESTResourceServiceImplTest.java

References: https://github.com/geosolutions-it/MapStore2/issues/9550

[ISSUE #9550] Show creator/editor in 'Edit properties'

---

pom.xml

Fix #344. Remove NVD check by default

Fix #344. Remove NVD check by default

---

pom.xml
src/cli/pom.xml
src/core/model/pom.xml
src/core/persistence/pom.xml
src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
src/core/security/pom.xml
src/core/security/src/main/java/it/geosolutions/geostore/core/security/JSONExpressionUserMapper.java
src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStoreDigestPasswordEncoder.java
src/core/security/src/main/java/it/geosolutions/geostore/core/security/password/GeoStorePBEPasswordEncoder.java
src/core/services-api/pom.xml
src/core/services-impl/pom.xml
src/modules/rest/api/pom.xml
src/modules/rest/auditing/pom.xml
src/modules/rest/client/pom.xml
src/modules/rest/extjs/pom.xml
src/modules/rest/impl/pom.xml
src/modules/rest/test/pom.xml
src/pom.xml
src/web/app/pom.xml

- [Backport 2.1.x] Dependency updates (#340)
- [Backport 2.1.x] Fix #344. Remove NVD check by default (#345)

[Backport 2.1.x] Dependency updates and NVD skip (#340) (#345)

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakLoginService.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakCookieUtils.java

Opened in favor of https://github.com/geosolutions-it/geostore/pull/358

[FIXES #2971] MapStore - SSO keycloak kerberos

---

pom.xml

CI yaml already run with java 11...

Update mvn compiler plugin in root pom.xml to run with java 11

---

src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java

See #420 for the context. This PR is the mentioned patch applied against the master branch.

GeoStoreInit - shunt password encoding (#420)

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserServiceAuthenticationProvider.java

Improve logging on authentication to check the effective error of login, that now is not logged properly

Improved logging on authentication

---

src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java

This PR should fix https://github.com/geosolutions-it/MapStore2/issues/11069 introduced by removing https://github.com/geosolutions-it/geostore/pull/421/files#diff-5bed3775ae8e25d856669b6ba5ad0e74df7802bb1befe52c22c10131b731eb7cL119

Fix missing PWEncoder set

---

.github/workflows/CI.yml
src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourcePermissionServiceImpl.java
src/core/services-impl/src/main/java/it/geosolutions/geostore/services/TagServiceImpl.java
src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourcePermissionServiceImplTest.java
src/core/services-impl/src/test/java/it/geosolutions/geostore/services/TagServiceImplTest.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserServiceAuthenticationProvider.java
src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java

Backporting relevant updates for 2.3 version from master

---

src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java

(cherry picked from commit 4d22a6d700f05e53e78b91d50ae42f34eb112ab3)

[Backport to 2.3.x][FIXES #426] Support for direct integration on security settings (#429)

---

src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/SecurityDAOTest.java
src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
src/web/app/pom.xml
src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java

Cherry-picked commit https://github.com/geosolutions-it/geostore/commit/4d2e2cb630db03958d2f831d2ef40bd077f88e8f.

[Backport to 2.3.x] Removed editor overwrite at resource permission update (#433).

---

.github/workflows/CI.yml
pom.xml

* upgrade spring framework to version 5.3.39
* Roll your own cache step
* Roll your own cache step
---------

[Backport to 2.3.x] upgrade spring framework to version 5.3.39 (#423)

---

src/core/services-impl/src/main/java/it/geosolutions/geostore/services/TagServiceImpl.java
src/core/services-impl/src/test/java/it/geosolutions/geostore/services/TagServiceImplTest.java

Backports #439 on 2.3.x branch.

[Backport to 2.3.x] Fixed tag update bug (#439).

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/GeoStoreAuthenticationFilterTest.java

https://github.com/geosolutions-it/geostore/pull/410

[Backport 2.3.x] [FIXES #409] Add Username Remapping & Uppercase Group Names Support in OAuth2 Authentication Filter

---

src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java

* Adding ID_TOKEN log info ad Debug level
* Trimming roles and groups config keys
* code formatting
(cherry picked from commit d43482275c8a663ce38df73241ec9988144f8e09)

[Backport 2.3.x] Adding ID_TOKEN log info ad Debug level (#442)
