geosolutions-it/geostore

- doc/sql/geofence-geostoreUsersIntegration_scripts/postgres/001_setup_geostore_geofence_db.sql
- doc/sql/geofence-geostoreUsersIntegration_scripts/postgres/002_create_schema_geostore_postgres.sql
- doc/sql/geofence-geostoreUsersIntegration_scripts/postgres/003_create_schema_geofence_postgres.sql
- doc/sql/geofence-geostoreUsersIntegration_scripts/readme.markdown
This pull request move the DDL scripts for the database creation from the geosolutions/geofence repository to geosolutions/geostore repository.
Regarding the matter of the schema trigger [see the postgres doc about the parameter name](http://www.postgresql.org/docs/9.1/static/sql-createtrigger.html), the schema of the trigger is inherithed by the table where the trigger work on.
> Sql creation scripts for the geofence integration

- src/server/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/RESTMiscService.java
- src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTMiscServiceImpl.java
- src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/GeoStoreLdapAuthoritiesPopulator.java
- src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/GroupsRolesService.java
- src/server/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserLdapAuthenticationProvider.java
- src/server/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/MockLdapAuthoritiesPopulator.java
- src/server/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/UserLdapAuthenticationProviderTest.java
- src/server/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/MockedUserGroupService.java
- src/server/web/app/src/main/java/it/geosolutions/geostore/init/LDAPInit.java
- src/server/web/app/src/main/resources/geostore-spring-security.xml
Added a new LDAPInit initializer to be enabled when LDAP security is enabled.
The initializer synchronizes all groups from the LDAP repo upon GeoStore start. Only adding is supported (no update or delete)
A new rest call allows synchronization to occur also after GeoStore start (/misc/reload/ldap)
> Fixes #115: LDAP groups synch on init and reload rest call

- src/pom.xml
Version 3.2 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/
> Upgrade Apache Commons Collections to v3.2.2

- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/providers/StringTextProvider.java
- src/modules/rest/api/src/test/java/it/geosolutions/geostore/services/providers/StringConversionTest.java
- src/modules/rest/impl/src/main/resources/applicationContext.xml
- src/web/app/src/test/resources/applicationContext-test.xml
Fix #168.
This fixes issues due to wrong encoding of strings like `àèìòù when update the StoredData. 
Implementing a StringTextProvider that replaces default behiviour when a provider is not matched for string.
> Fix #168. Created custom provider for pure text request body

- src/modules/rest/extjs/src/main/resources/applicationContext.xml
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/FixedCacheControlOutInterceptor.java
- src/modules/rest/impl/src/main/resources/applicationContext.xml
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/FixedCacheControlOutInterceptorTest.java
Added an interceptor to all requests that adds the header:
```
Cache-Control: no-cache
```
to the response headers.
> Fix #171. Add fixed CacheControl interceptor

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/ResourceDAOImpl.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/RESTResourceService.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTServiceImpl.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/service/impl/RESTServiceImplTest.java
Actually Access rules from `ResourceDAOImpl.findUserSecurityRule` returns all rules available instead of returning rules that match user and . 
`RESTServiceImpl` expects only to find only one result (that is not properly correct because there is not any check about unique rules for same user/resource), so it gets the first rule available and checks this rule to find out read or write access information. But because of the bug above, any rule found on the db before the user's one is valid. So it returns true anyway. 
I changed this behavior to check all rules returned by the ResourceDAOImpl and ignore the ones not referred to the user. 
NOTE: I implemented a fix that ignores not valid rules in `RESTServiceImpl` because this part is testable ( test ResourceDAOImpl is hard instead) and …
> Fix #180. Filter properly user rules in RESTServiceImpl

- doc/sql/002_create_schema_oracle.sql
- doc/sql/002_create_schema_postgres.sql
- src/core/model/src/main/java/it/geosolutions/geostore/core/model/SecurityRule.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/AttributeTest.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/Marshaler.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/SecurityRuleTest.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/UserGroupTest.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ResourceDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/SecurityDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/StoredDataDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/ExternalSecurityDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/ResourceDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/StoredDataDAOImpl.java
- src/core/persistence/src/main/resources/applicationContext.xml
- src/core/persistence/src/main/resources/securityapplicationContext.xml
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/BaseDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ExternalSecurityDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/SecurityDAOTest.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/StoredDataServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/HeadersAuthenticationFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/Convert.java
* changes to db security table to add explicit fields for username and groupname (to be used instead of ids when authentication is externalized)
* centralized security stuff in SecurityDAO, so that we can plug a new implementation for external authentication
* removed some dependencies from user / groups id where not needed
* introduced ExternalSecurityDAO implementation
> Implement support to manage permissions for external authentication

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/User.java
- src/core/model/src/main/java/it/geosolutions/geostore/core/model/UserGroup.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/UserTest.java
- src/core/persistence/pom.xml
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/LdapBaseDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserGroupDAOTest.java
- src/core/security/src/main/java/it/geosolutions/geostore/core/ldap/IterableNamingEnumeration.java
- src/core/security/src/main/java/it/geosolutions/geostore/core/ldap/MockContextSource.java
- src/core/security/src/main/java/it/geosolutions/geostore/core/ldap/MockDirContextOperations.java
- src/core/security/src/test/java/it/geosolutions/geostore/core/security/ldap/CustomAttributesLdapUserDetailsMapperTest.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ServiceTestBase.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/UserServiceImplTest.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/UserGroupList.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTUserGroupServiceImpl.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/GeoStoreLdapAuthoritiesPopulatorTest.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/MockLdapAuthenticator.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/MockedUserService.java
- src/web/app/src/main/resources/geostore-spring-security.xml
Enabling these DAOs (see example in xml) users and groups are fetched from LDAP instead of the internal database.
Current support is limited to API calls required by MapStore permissions handling.
> #195: Initial implementation of read-only LDAP User and UserGroup DAOs

- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/RESTResourceService.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/RESTAttribute.java
- src/modules/rest/impl/pom.xml
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTResourceServiceImpl.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/service/impl/RESTResourceServiceImplTest.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/MockSecurityContext.java
- src/pom.xml
Added REST API PUT API compliant, with value in the body. 
This should avoid issue https://github.com/georchestra/mapstore2-georchestra/issues/101 together with a different request from MapStore, using the new entry. 
The request should be like this: 
`PUT "/resource/{resource-id}/attributes/"`
```json
{
"restAttribute": {
"name": "test",
"value": "MyTest1"
}
}
```
> Add compliant attribute update REST API

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/HeadersAuthenticationFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/GroupMapper.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/SpelMapper.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/HeadersAuthenticationFilterTest.java
- src/pom.xml
This PR allows to remove from role headers a prefix for mapping groups.
> Allow to remove header group prefix

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/enums/GroupReservedNames.java
- src/core/model/src/test/java/it/geosolutions/geostore/core/model/GroupReservedNamesTest.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/LdapBaseDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/BaseDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserGroupDAOTest.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/UserServiceImplTest.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/SessionTokenAuthenticationFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/UserLdapAuthenticationProvider.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/SessionTokenAuthenticationFilterTest.java
Improves usability of LDAP compatible DAOs, for a better integration with MapStore authentication.
In particular:
* all user configuration (included groups and role, via the new adminRoleGroup property) are fetched by the UserDAO
* write operations fail silently instead of throwing, waiting for an explicit support for readonly DAOs from the services
* more fallbacks to using search by name when search by id does not return a valid user (LDAP id is fake, and cannot be used for searching)
> #219: improvements to the LDAP compatible DAOs to fully replace the standard ones in a MapStore standard security configuration

- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserGroupService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ServiceTestBase.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/UserServiceImplTest.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/MockedUserGroupService.java
When updating a user, there is a check in UserServiceImpl to match the DTO user groups with existing groups in database.
Unfortunately, groups stored in database where filtered to remove the special everyone group, but the DTO user's group were not, so there was always a mismatch.
The fix in this PR changes the code so that also the DTO groups are filtered, restore the correct behaviour.
The fix is a one-liner. The remaining part of the PR is needed to add a unit test for this fix.
> #6825: fixes password change for MapStore

- src/pom.xml
[Backport 1.7.x] Upgrading log4j to a version that does not support RCEs (#243)
> [Backport 1.7.x] Upgrading log4j to a version that does not support RCEs (#243)

- src/modules/rest/impl/pom.xml
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/WebServiceTokenAuthenticationFilter.java
- src/pom.xml
- src/web/app/pom.xml
Updates the HTTP client to 4.5.13.
> Corporate proxy issue prevents connections between MS and GN

- pom.xml
- src/cli/pom.xml
- src/core/model/pom.xml
- src/core/persistence/pom.xml
- src/core/pom.xml
- src/core/security/pom.xml
- src/core/services-api/pom.xml
- src/core/services-impl/pom.xml
- src/modules/pom.xml
- src/modules/rest/api/pom.xml
- src/modules/rest/auditing/pom.xml
- src/modules/rest/client/pom.xml
- src/modules/rest/extjs/pom.xml
- src/modules/rest/impl/pom.xml
- src/modules/rest/pom.xml
- src/modules/rest/test/pom.xml
- src/pom.xml
- src/web/app/pom.xml
- src/web/pom.xml
There was a recent update in 1.8.x to upgrade HTTPClient from 3.x to 4.x
This resulted in MapStore2-C039 inheriting that HTTP upgrade although one of its module was still using the older one, so it ended up in using 2 different versions.
https://github.com/geosolutions-it/webmapper-halliburton/issues/2327#issuecomment-1029150049
So the idea was to have a 1.8.x branch with the commit right before that HTTP client upgrade and have master moving to 1.9.x
> Update master to 1.9.x

- src/core/security/src/main/java/it/geosolutions/geostore/core/security/SimpleGrantedAuthoritiesMapper.java
- src/core/security/src/test/java/it/geosolutions/geostore/core/security/SimpleGrantedAuthoritiesMapperTest.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/GeoStoreLdapAuthoritiesPopulator.java
Proposed changes:
- Separating mappers for roles and concepts
- Added configuration to prevent unmapped authorities to be stored
- Keep older bean definition in place for back compatibility
- Improved logging 
---
After upgrading, if you don't change your xml configuration, you may get this error in the logfile:
`AuthoritiesMapper is deprecated, please set roleMapper and groupMapper separately`
This means you have, in the `geostoreLdapProvider` bean definition, the setter for the property `authoritiesMapper` (which is now deprecated).
In order to maintain the old behaviour, the `authoritiesMapper` will set the new 2 properties, `roleMapper` and `groupMapper`, that can now be separately defined.
Once the fix is applied, you may want to:
In `geostoreLdapProvider`, change the entry:
```xml …
```
> #265 LDAP groups and roles concepts are mixed

- src/pom.xml
Follow up the changes in googlecode genric dao and spring 5.3.18 and updates maven versions.
> change hibernate and google genric-dao versions

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserGroupDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/search/GeoStoreISearchWrapper.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/BaseDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ldap/UserDAOTest.java
Avoid the loading the Users nested into UserGroup when returning user search results.
> (#290) LDAP UserDAO avoid loading groups' nested users

- src/modules/rest/impl/pom.xml
-XOM dependencies is introducing xerces transitive dependency that has been causing trouble to geostore startup.
- the depedency seems to be related to serialization and deserialization of XML payloads and seems to not be actually needed. 
- Build is successful and testing endpoint with xml output/input doesn't cause any error once xom is removed.
> remove xom depedencies

- doc/sql/002_create_schema_oracle.sql
- doc/sql/002_create_schema_postgres.sql
- doc/sql/migration/h2/h2-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/h2/h2-migration-from-v.2.0.0-to-v2.1.0.sql
- doc/sql/migration/oracle/oracle-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/oracle/oracle-migration-from-v.2.0.0-to-v2.1.0.sql
- doc/sql/migration/postgresql/postgresql-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
- src/core/model/src/main/java/it/geosolutions/geostore/core/model/Resource.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/SecurityDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourceService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/dto/ShortResource.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourceServiceImplTest.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ServiceTestBase.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/RESTResource.java
- src/modules/rest/api/src/test/java/it/geosolutions/geostore/services/rest/utils/FilterUnmarshalTest.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/ServiceTestBase.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTBackupServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTResourceServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/Convert.java
Part of geosolutions-it/MapStore2#9583
> [Fixes #9583] Unadvertised resources

- doc/sql/002_create_schema_oracle.sql
- doc/sql/002_create_schema_postgres.sql
- doc/sql/migration/h2/h2-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/h2/h2-migration-from-v.2.0.0-to-v2.1.0.sql
- doc/sql/migration/oracle/oracle-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/oracle/oracle-migration-from-v.2.0.0-to-v2.1.0.sql
- doc/sql/migration/postgresql/postgresql-migration-from-v.1.5.0-to-v2.0.0.sql
- doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql
- src/core/model/src/main/java/it/geosolutions/geostore/core/model/Resource.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/SecurityDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/ResourceDAOTest.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/SecurityDAOTest.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/dto/ShortResource.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ResourceServiceImplTest.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/SearchConverterTest.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/ServiceTestBase.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/RESTResource.java
- src/modules/rest/api/src/test/java/it/geosolutions/geostore/services/rest/utils/FilterUnmarshalTest.java
- src/modules/rest/client/src/test/java/it/geosolutions/geostore/services/rest/AdministratorGeostoreClientTest.java
- src/modules/rest/client/src/test/java/it/geosolutions/geostore/services/rest/GeoStoreClientTest.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/ServiceTestBase.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTBackupServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTResourceServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/Convert.java
Part of geosolutions-it/MapStore2#9550
> [Fixes #9550] Show creator/editor in 'Edit properties'

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
The refreshed session token from the doRefresh method is ignored.
The sessionToken == null test on line 120 is always true and the expiration of the current (possibly expired) token is used for the session token.
> refreshed token is ignored

- src/pom.xml
Bumps org.mortbay.jetty:jetty from 6.1.14 to 6.1.23.
---
updated-dependencies:
- dependency-name: org.mortbay.jetty:jetty dependency-type: direct:production ...
> Bump org.mortbay.jetty:jetty from 6.1.14 to 6.1.23 in /src

- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/SessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/SessionServiceDelegateImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/IdPConfiguration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/TokenAuthenticationCache.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakSessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/DiscoveryClient.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/Oauth2LoginService.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/google/GoogleSessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectConfiguration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectLoginService.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectSessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/utils/GeoStoreContext.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/OAuth2SessionServiceTest.java
```
java.lang.NullPointerException
it.geosolutions.geostore.services.rest.security.oauth2.OAuth2SessionServiceDelegate.retrieveAccessToken(OAuth2SessionServiceDelegate.java:196)
it.geosolutions.geostore.services.rest.security.oauth2.OAuth2SessionServiceDelegate.refresh(OAuth2SessionServiceDelegate.java:96)
it.geosolutions.geostore.services.rest.impl.RESTSessionServiceImpl.refresh(RESTSessionServiceImpl.java:199)
it.geosolutions.geostore.services.rest.impl.RESTSessionServiceImpl.refresh(RESTSessionServiceImpl.java:226)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java …
```
> [FIXES #2408] Refresh Token and Logout OIDC requests

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakLoginService.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakCookieUtils.java
Opened in favor of https://github.com/geosolutions-it/geostore/pull/359
> [FIXES #2971] MapStore - SSO keycloak kerberos

- src/cli/pom.xml
- src/core/model/pom.xml
- src/core/persistence/pom.xml
- src/core/pom.xml
- src/core/security/pom.xml
- src/core/services-api/pom.xml
- src/core/services-impl/pom.xml
- src/modules/pom.xml
- src/modules/rest/api/pom.xml
- src/modules/rest/auditing/pom.xml
- src/modules/rest/client/pom.xml
- src/modules/rest/extjs/pom.xml
- src/modules/rest/impl/pom.xml
- src/modules/rest/pom.xml
- src/modules/rest/test/pom.xml
- src/web/app/pom.xml
- src/web/pom.xml
Due to the issue #365 , the Bump version was not applied to all the modules.
So this have to be updated manually before to go.
> Fix versions for 2.3-SNAPSHOT

- src/pom.xml
Fix #365 .
The issue was caused by the new profiles, activated by the `qa` property set to true in pom, that made skip the `default` profile that contained all modules.
I solved this issue once for all removing the  default profile and moving the modules that should be always build in the  root of the pom.
So only additional modules will be activated by profiles (in particular `cli`)
> Fix modules

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/GeoStoreKeycloakAuthProvider.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreSecurityConfiguration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectFilter.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectSecurityConfiguration.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/openid_connect/OpenIdConnectIntegrationTest.java
The current PR addresses few issues mainly related to the `refreshToken` endpoint:
1. The main issue is due to the fact that if the current condition is met `if ((expiresIn == null || fiveMinutesFromNow.after(expiresIn)) && refreshToken != null)`, i.e. the `refreshToken` is not expired yet, the `sessionToken` sent back will be `NULL` resulting in an `204: empty response` causing the client to lose the current `accessToken`
2. The `cache bean` of the `OIDC` has a wrong name causing a `context exception` when trying to retrieve it from a new `thread`
3. Generally speaking the code checks only for `accessToken` nullability but consider it valid in the case it's `empty`, and this is an error and must be threated as an error.
4. The `doRefresh` method does not send the `client_id` to the IDP …
> [FIXES #2408] C206-DEUTSCHE_BAHN-2023-SUPPORT - SSO - Supported OpenID services

- pom.xml
- src/modules/rest/impl/pom.xml
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/openid_connect/RefreshTokenServiceTest.java
This PR improves the way how GeoStore handles the `refresh-token` request by:
- Checking the refresh token despite the access token expiration; a refresh token expiration might be set too
- Making sure the new access token and refresh token will be sent bach to the sender
- Attempting the refresh token request in case of temporary network/communication issues
> Improvements with OKTA OIDC provider integration

- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/SessionToken.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeycloakSessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2SessionServiceDelegate.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/openid_connect/OpenIdConnectConfiguration.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/oauth2/openid_connect/RefreshTokenServiceTest.java
In this updated version of the `SessionDelegate` upon a `Refresh` request the backend also checks:
- The remote `refresh-token` request is returning a valid code
- The current `accessToken` is still valid in the case the previous one fails for some reason
Other than that, the `SessionToken` bean has been updated in order to return back also a `Warning` or `Error` message with the explanation of the failuers.
As an instance, in the case the remote `refresh-token` request throws a `UserRedirectException` because it need manual validation but the current `AccessToken` is still valid (not expired), the `SessionToken` will be still valid, by using the current `AccessToken` but it will provide a `Warning` message like the one below
```json
{
"sessionToken": {
"access_token": …
```
> OIDC okta testing

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/Resource.java
- src/core/model/src/main/java/it/geosolutions/geostore/core/model/User.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/PermissionService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourceService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/SecurityService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/PermissionServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/model/SecurityRuleList.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/model/ExtShortResource.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/RESTExtJsService.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTServiceImpl.java
Changes as per #380:
- Added following information to the resource fetching, controlled by query parameters:
- attributes (parameter `includeAttributes`): the returned payload contains an `AttributeList` element
- permissions (parameter `includePermissions`): the returned payload contains a `SecurityRuleList` element
Example:
```xml
<ShortResource>
<advertised>false</advertised>
<canDelete>false</canDelete>
<canEdit>false</canEdit>
<creation>2025-01-17T19:04:03.379+00:00</creation>
<creator>Y</creator>
<editor>editore</editor>
<id>101</id>
<name>user owned readonly</name>
<attributeList>
<Attribute>
<name>resource 101 attr</name>
<type>STRING</type>
<value>prova</value>
</Attribute>
</attributeList>
<securityRuleList>
<SecurityRule>
<canRead>true</canRead>
<canWrite>false</canWrite> …
```
> Review of endpoints to return a single resource

- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserGroupService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
- src/modules/rest/api/src/main/java/it/geosolutions/geostore/services/rest/RESTUserGroupService.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTUserGroupServiceImpl.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/keycloak/MockUserGroupService.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/service/impl/RESTUserGroupServiceImplTest.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/services/rest/utils/MockedUserGroupService.java
Changes as per #381:
- added `nameLike`query parameter to the endpoint `/rest/usergroups`, to let the caller filter by usergroup name
The name of the parameter is aligned to the path parameters used for similar purposes all around the API; in this case it is a query parameter to better adhere to ReST standards.
For the same endpoint, pagination was already in place, so nothing has been done, apart from creating a unit test to verify the functionality.
Closes #381
> Review of usergroup endpoint

- src/core/services-api/src/main/java/it/geosolutions/geostore/services/dto/search/AndFilter.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/dto/search/OrFilter.java
Group filter was missing in the list of parsable filters in the AND and OR search filters.
This caused to have filters like the following ignored:
```xml
<OR>
<FIELD>
<field>NAME</field>
<operator>ILIKE</operator>
<value>%user%</value>
</FIELD>
<AND>
<NOT>
<CATEGORY>
<operator>EQUAL_TO</operator>
<name>MAP</name>
</CATEGORY>
</NOT>
<NOT>
<GROUP>
<operator>ILIKE</operator>
<names>%group%</names>
</GROUP>
</NOT>
</AND>
</OR>
```
> Fixed group filter parsing in boolean filters.

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/Resource.java
This change follows the issue reported [here](https://github.com/geosolutions-it/MapStore2/pull/10731#pullrequestreview-2578725752).
The annotation used to serialize and deserialize the Resource entity was removed causing regression.
This PR restores it.
> Restored resource entity XML serialization.

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourcePermissionService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourcePermissionServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
The refactoring operated on the user permissions verification has introduced redundant checks to discard unadvertised resources, that slowed the response time for `extjs/search/list` endpoint as reported in https://github.com/geosolutions-it/MapStore2/issues/10794.
These changes remove those redundant checks, leaving the filtering only on the DB query execution.
> Revised unadvertised resources filtering.

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/SecurityDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/UserDAO.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/UserDAOImpl.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourcePermissionService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/ResourceService.java
- src/core/services-api/src/main/java/it/geosolutions/geostore/services/UserService.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourcePermissionServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserServiceImpl.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
These changes aim to address the slowness reported on the MapStore main page loading in [issue #10794](https://github.com/geosolutions-it/MapStore2/issues/10794).
Previously, the logic for checking resource permissions was inverted, retrieving permissions from user and user group security rules. This approach led to ORM N+1 issues, significantly impacting performance.
The logic has now been restored to check permissions from the resources themselves, reducing database accesses to a minimum.
> Optimized user permission checks on resource.

- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
Having added a new `LAZY` fetched association to the resource for favorites, this was not added in the fetch for the full resource loading from the DB, causing an `no Session` error in hibernate.
These changes fixes https://github.com/geosolutions-it/MapStore2/issues/10801.
> Fixed missing favorites fetch in full resource loading.

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/Resource.java
Fetching the full resource object was causing serialization errors because of the lazy loading of the `favoritedBy` collection of `User` entities. The attributes of the user were therefore missing, throwing the exception reported in https://github.com/geosolutions-it/MapStore2/issues/10781#issuecomment-2681674492.
These changes fix the problem, avoiding returning the `favoritedBy` collection from the serialized resource.
> Fixed full resource serialization

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
Enhanced Ownership Checks
Expanded resourceUserOwnership and resourceGroupOwnership predicates to also match on SecurityRule.username and SecurityRule.groupname when IDs differ.
New Test Coverage
Introduced ResourcePermissionServiceImplTest with two positive tests:
testCanReadByUsernameMatch
testCanReadByGroupnameMatch
Prior to this change, a security rule only granted access if the user/group ID matched exactly. In cases where the rule was created with a legacy or external identifier (username or groupname) that didn’t map directly to the internal ID, valid principals were being wrongly denied. Supporting name-based matching closes this gap.
Backward-compatible: ID-based matching remains unchanged; name-based is only an additional allowance.
Granularity: Exact matching on both …
> [FIXES #426] Support for direct integration on security settings (#429)

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
- src/modules/rest/impl/src/test/java/it/geosolutions/geostore/rest/security/GeoStoreAuthenticationFilterTest.java
References: https://github.com/geosolutions-it/geostore/issues/409
This pull request introduces two new features and some refactoring improvements in the OAuth2 authentication filter:
**New Features**
1. Username Remapping from idToken Claims:
- The filter now decodes the `idToken` only once using a helper (`JWTHelper`).
- If the configuration provides non-blank values for both `principalKey` and `uniqueUsername`, and the incoming username (from the principal claim) matches the expected value, it is remapped to the value found in the unique username claim.
- This ensures that the system always works with a consistent unique identifier for user lookup and creation.
2. Enforce Uppercase Group Names:
- A new configuration parameter `groupNamesUppercase` has been added.
- When enabled, groups …
> [FIXES #409] Add Username Remapping & Uppercase Group Names Support in OAuth2 Authentication Filter

- geoserver/role/geostore/oracle/rolesddl.xml
- geoserver/role/geostore/oracle/rolesdml.xml
- geoserver/usergroup/geostore/oracle/usersddl.xml
- geoserver/usergroup/geostore/oracle/usersdml.xml
When working through the Mapstore integration with Geoserver, for an Oracle 19c database, I found the process failed when creating the User Group Service and Role Service due to errors in the userddl.xml and roleddl.xml files included in the geostore-master.zip file I downloaded.
I have modified these files so they now work. I have also changed the table names so they are now prefixed with gs_
> Update of oracle *ddl.xml and *dml.xml files in geoserver/role and geoserver/usergroup

- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2Configuration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
Ref: #409
- Introducing the uniqueUsername configuration parameter in order to …allow specifying which clam to be used from the JWT token as username value
- Introducing the groupNamesUppercase configuration parameter  in order to force the insertion of roles/groups claims from the JWT token uppercase
> [Backport 2.2.x] [FIXES #409] Add Username Remapping & Uppercase Group Names Support in OAuth2 Authentication Filter

- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/impl/SecurityDAOImpl.java
- src/core/persistence/src/test/java/it/geosolutions/geostore/core/dao/SecurityDAOTest.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
- src/web/app/pom.xml
- src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java
These changes aim to address the issue reported in https://github.com/geosolutions-it/MapStore2/issues/11098.
Previously, when permission were updated for a resource, the user of the permission was erroneously set as the `editor` of the resource, creating inconsistencies at the frontend.
This behavior was not expected, so it has been removed.
> Removed editor overwrite at resource permission update.

- pom.xml
- src/cli/pom.xml
- src/cli/src/main/java/it/geosolutions/geostore/cli/H2ToPgSQLExporter.java
- src/core/persistence/pom.xml
- src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/LdapBaseDAOImpl.java
- src/core/security/pom.xml
- src/core/services-api/pom.xml
- src/core/services-impl/pom.xml
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/IdPConfiguration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/keycloak/KeyCloakConfiguration.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
- src/pom.xml
- Bumps commons-lang-version to version 3.17.0 in order to be aligned with the MapStore ones
- Bumps commons-codec-version to version 1.16.0 since the 1.4.0 are very old; MapStore does not use those libraries
- SL4J: Adding SLF4J jars does not replace Log4j 2 – it just puts a lightweight, standard façade in front of it and this is what MapStore actually does already; like this geostore is more aligned with MapStore
- Cobertura does not work anymore with Java 8; it has been replaces with JaCoCo which is Java 11+ compatible
> Align geostore dependencies with the MapStore ones

- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/TagServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/TagServiceImplTest.java
These changes aim to address the issue reported in https://github.com/geosolutions-it/MapStore2/issues/11174.
An unwanted check for duplicated tags during update has been removed.
Tests have been added to assess the correct behaviour during tags update and duplicates creation.
> Fixed tag update bug.

- src/core/model/src/main/java/it/geosolutions/geostore/core/model/UserGroup.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
- src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/OAuth2GeoStoreAuthenticationFilter.java
This small patch ensure the OAuth2 service sanitize the user group names avoiding a DB constraint error.
> [Backport 2.3.x] Making OAuth2GeoStoreAuthenticationFilter resilient to possible group name duplication

- src/core/services-api/src/main/java/it/geosolutions/geostore/services/dto/ShortResource.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/ResourceServiceImpl.java
- src/core/services-impl/src/main/java/it/geosolutions/geostore/services/UserGroupServiceImpl.java
- src/core/services-impl/src/test/java/it/geosolutions/geostore/services/UserGroupServiceImplTest.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/model/ExtShortResource.java
- src/modules/rest/extjs/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImpl.java
- src/modules/rest/extjs/src/test/java/it/geosolutions/geostore/services/rest/impl/RESTExtJsServiceImplTest.java
Backports https://github.com/geosolutions-it/geostore/pull/448 on 2.3.x branch.
> [Backport to 2.3.x] Added `canCopy` attribute to ShortResource representation. (#448)
